#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CFDOT_DIR=${DIR}/..

# COMMANDS=`go run main.go | egrep "^  [A-Za-z]"`
# grep "${COMMANDS}" ${CFDOT_DIR}/README.md

FILE_TXT=`grep "^  [A-Za-z]" README.md | grep -v "^  cfdot" | awk '{print $1}' | sort`
CMD_TXT=`grep -h 'Use:' commands/*.go --exclude *_test.go --exclude root.go | awk '{print $2}' | sed "s/\"\|,//g" | sort`

OUTPUT=`comm -3 <(echo $FILE_TXT) <(echo $CMD_TXT)`

if [[ $OUTPUT != '' ]]; then
 echo "README is not up to date with cfdot commands"
 exit 1
fi
